version: '3.9'
services:
  db:
    image: 'mysql:8.0'
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - 'db_data:/var/lib/mysql'
    command: '--default-authentication-plugin=mysql_native_password'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel-api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - './backend/src:/var/www/html'
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_URL: 'http://localhost:8000'
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db
  nginx:
    image: 'nginx:1.25'
    container_name: nginx
    restart: unless-stopped
    ports:
      - '8000:80'
    volumes:
      - './backend/src:/var/www/html'
      - './backend/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    depends_on:
      - backend
  frontend:
    environment:
      - 'VITE_API_BASE_URL=http://localhost:8000/api'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-spa
    restart: unless-stopped
    working_dir: /app
    ports:
      - '5173:5173'
    volumes:
      - './frontend:/app'
    command:
      - npm
      - run
      - dev
      - '--'
      - '--host'
volumes:
  db_data: null
